# Generated by Django 4.1 on 2022-08-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(null=True)),
                ('active', models.BooleanField(null=True)),
                ('image', models.ImageField(null=True, upload_to='products')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
